name: openapi_generator
description: Generator for openapi client sdk inspired by the npm implementation of openapi-generator-cli.
version: 4.0.0
homepage: https://github.com/gibahjoe/openapi-generator-dart
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: '>=0.12.6 <=3.0.0'
  source_gen: '>=1.0.0 <=2.0.0'
  path: '>=1.0.0 <=2.0.0'
  analyzer: '>=1.4.0 <=5.0.0'

  openapi_generator_annotations:
  openapi_generator_cli:

dependency_overrides:
  openapi_generator_annotations:
    path: ../openapi-generator-annotations
  openapi_generator_cli: 
    path: ../openapi-generator-cli

dev_dependencies:
  pedantic:

